name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get install libglfw3 libglfw3-dev libvulkan1 libvulkan-dev libassimp5 libassimp-dev
    - name: make linux-vulkan-examples
      run: make linux-vulkan-examples
